name: Rust with LLVM

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  install-llvm:
    runs-on: ubuntu-latest
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16.0"

  build:
    runs-on: ubuntu-latest
    needs: install-llvm
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: RUST_BACKTRACE=1 cargo build --verbose
      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --verbose
