name: Rust with LLVM

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  install-llvm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

  build:
    runs-on: ubuntu-latest
    needs: install-llvm
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: RUST_BACKTRACE=FULL cargo build --verbose
      - name: Run tests
        run: RUST_BACKTRACE=FULL cargo test --verbose
